In [2]:
import pandas as pd
import numpy as np
import os

# download terror dataset from google drive link (this is much faster than uploading it yourself)
if not os.path.exists('gtdDataSet.csv'):
    !gdown --id 1VqQs1vz2TZdzR6NUo9klkgl1eI4LFpgW

Downloading...
From: https://drive.google.com/uc?id=1VqQs1vz2TZdzR6NUo9klkgl1eI4LFpgW
To: /content/gtdDataSet.csv
100% 184M/184M [00:01<00:00, 120MB/s]

In [6]:
# read in the dataset from a file
df = pd.read_csv('OECD_Leading_DataSet.csv')
df

     LOCATION INDICATOR   SUBJECT  ...     TIME     Value Flag Codes
0         GBR       CLI  AMPLITUD  ...  2005-02  100.2482        NaN
1         GBR       CLI  AMPLITUD  ...  2005-03  100.2449        NaN
2         GBR       CLI  AMPLITUD  ...  2005-04  100.2153        NaN
3         GBR       CLI  AMPLITUD  ...  2005-05  100.1706        NaN
4         GBR       CLI  AMPLITUD  ...  2005-06  100.1293        NaN
...       ...       ...       ...  ...      ...       ...        ...
1395      CAN       CLI  AMPLITUD  ...  2021-05  100.5329        NaN
1396      CAN       CLI  AMPLITUD  ...  2021-06  100.7005        NaN
1397      CAN       CLI  AMPLITUD  ...  2021-07  100.8202        NaN
1398      CAN       CLI  AMPLITUD  ...  2021-08  100.8623        NaN
1399      CAN       CLI  AMPLITUD  ...  2021-09  100.8557        NaN

[1400 rows x 8 columns]

In [19]:
# group by country and subtract the current row by 3 rows before
df['diffs'] = df.groupby(['LOCATION'])['Value'].diff(3)
# reset the index to return the dataframe to its original form
df.reset_index(drop=True, inplace=True)
# show the updated dataframe
df.head(10)

  LOCATION INDICATOR   SUBJECT  ...     Value Flag Codes   diffs
0      GBR       CLI  AMPLITUD  ...  100.2482        NaN     NaN
1      GBR       CLI  AMPLITUD  ...  100.2449        NaN     NaN
2      GBR       CLI  AMPLITUD  ...  100.2153        NaN     NaN
3      GBR       CLI  AMPLITUD  ...  100.1706        NaN -0.0776
4      GBR       CLI  AMPLITUD  ...  100.1293        NaN -0.1156
5      GBR       CLI  AMPLITUD  ...  100.0971        NaN -0.1182
6      GBR       CLI  AMPLITUD  ...  100.0654        NaN -0.1052
7      GBR       CLI  AMPLITUD  ...  100.0354        NaN -0.0939
8      GBR       CLI  AMPLITUD  ...  100.0230        NaN -0.0741
9      GBR       CLI  AMPLITUD  ...  100.0548        NaN -0.0106

[10 rows x 9 columns]

In [20]:
# show the first 5 rows for the first 3 locations to show that a delta was calculated
df[df.LOCATION.isin(df.LOCATION.unique()[:3])].set_index(['LOCATION', 'TIME'])[['Value', 'diffs']].groupby(level=0).head(5)

                      Value    diffs
LOCATION TIME
GBR      2005-02  100.24820      NaN
         2005-03  100.24490      NaN
         2005-04  100.21530      NaN
         2005-05  100.17060 -0.07760
         2005-06  100.12930 -0.11560
ITA      2005-02   99.84733      NaN
         2005-03   99.65719      NaN
         2005-04   99.44277      NaN
         2005-05   99.25113 -0.59620
         2005-06   99.13202 -0.52517
JPN      2005-02  100.59520      NaN
         2005-03  100.56010      NaN
         2005-04  100.54800      NaN
         2005-05  100.56660 -0.02860
         2005-06  100.62440  0.06430

In [21]:
# read the dataset
terror_df = pd.read_csv('gtdDataSet.csv')
terror_df.head(5)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (4,31,33,54,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

        eventid  iyear  imonth  iday  ... INT_IDEO  INT_MISC INT_ANY  related
0  197000000001   1970       7     2  ...        0         0       0      NaN
1  197000000002   1970       0     0  ...        1         1       1      NaN
2  197001000001   1970       1     0  ...       -9         1       1      NaN
3  197001000002   1970       1     0  ...       -9         1       1      NaN
4  197001000003   1970       1     0  ...       -9         1       1      NaN

[5 rows x 135 columns]

In [10]:
terror_df['year-month'] = terror_df.apply(lambda x: f"{x.iyear}-{str(x.imonth).zfill(2)}", axis=1)

In [11]:
# manually create a dataframe holding country code conversions
country_codes = pd.DataFrame([
    ['United Kingdom', 'GBR'],
    ['Italy', 'ITA'],
    ['Japan', 'JPN'],
    ['France', 'FRA'],
    ['United States', 'USA'],
    ['Germany','DEU'],
    ['Canada', 'CAN']
], columns=['country_name', 'country_code'])
country_codes

     country_name country_code
0  United Kingdom          GBR
1           Italy          ITA
2           Japan          JPN
3          France          FRA
4   United States          USA
5         Germany          DEU
6          Canada          CAN

In [12]:
# add a column for country codes in order to merge the original dataframe
terror_df = terror_df.merge(country_codes, how='left', left_on='country_txt', right_on='country_name').drop(columns='country_name')
terror_df.head(10)

        eventid  iyear  imonth  iday  ... INT_ANY  related year-month  country_code
0  197000000001   1970       7     2  ...       0      NaN    1970-07           NaN
1  197000000002   1970       0     0  ...       1      NaN    1970-00           NaN
2  197001000001   1970       1     0  ...       1      NaN    1970-01           NaN
3  197001000002   1970       1     0  ...       1      NaN    1970-01           NaN
4  197001000003   1970       1     0  ...       1      NaN    1970-01           JPN
5  197001010002   1970       1     1  ...      -9      NaN    1970-01           USA
6  197001020001   1970       1     2  ...       0      NaN    1970-01           NaN
7  197001020002   1970       1     2  ...      -9      NaN    1970-01           USA
8  197001020003   1970       1     2  ...       0      NaN    1970-01           USA
9  197001030001   1970       1     3  ...       0      NaN    1970-01           USA

[10 rows x 137 columns]

In [13]:
# show countries without country codes
terror_df[terror_df['country_code'].isna()].country_txt.unique()

array(['Dominican Republic', 'Mexico', 'Philippines', 'Greece', 'Uruguay',
       'East Germany (GDR)', 'Ethiopia', 'Guatemala', 'Venezuela',
       'West Germany (FRG)', 'Switzerland', 'Jordan', 'Spain', 'Brazil',
       'Egypt', 'Argentina', 'Lebanon', 'Ireland', 'Turkey', 'Paraguay',
       'Iran', 'Colombia', 'Bolivia', 'Nicaragua', 'Netherlands',
       'Belgium', 'Australia', 'Pakistan', 'Zambia', 'Sweden',
       'Costa Rica', 'South Yemen', 'Cambodia', 'Israel', 'Poland',
       'Taiwan', 'Panama', 'Kuwait', 'West Bank and Gaza Strip',
       'Austria', 'Czechoslovakia', 'India', 'South Vietnam', 'Brunei',
       'Zaire', "People's Republic of the Congo", 'Portugal', 'Algeria',
       'El Salvador', 'Thailand', 'Haiti', 'Sudan', 'Morocco', 'Cyprus',
       'Myanmar', 'Afghanistan', 'Peru', 'Chile', 'Honduras',
       'Yugoslavia', 'Ecuador', 'New Zealand', 'Malaysia', 'Singapore',
       'Botswana', 'Jamaica', 'Chad', 'North Yemen', 'Andorra', 'Syria',
       'South Korea', 'United Arab Emirates', 'South Africa', 'Kenya',
       'Iraq', 'Somalia', 'Tanzania', 'Sri Lanka', 'Namibia', 'Bahamas',
       'Nigeria', 'Barbados', 'Trinidad and Tobago', 'Bangladesh',
       'Angola', 'Mauritania', 'Saudi Arabia', 'Djibouti', 'Indonesia',
       'Malta', 'Rhodesia', 'Soviet Union', 'Denmark', 'Western Sahara',
       'Guyana', 'Mozambique', 'Tunisia', 'Uganda', 'Norway', 'Lesotho',
       'Gabon', 'Libya', 'Bahrain', 'Hong Kong', 'Senegal', 'Zimbabwe',
       'Guinea', 'Grenada', 'New Hebrides', 'Belize', 'Guadeloupe',
       'Martinique', 'Vatican City', 'Albania',
       'Central African Republic', 'Seychelles', 'Dominica', 'Qatar',
       'Bulgaria', 'Suriname', 'Swaziland', 'Luxembourg', 'Iceland',
       'French Guiana', 'Falkland Islands', 'Burkina Faso',
       'New Caledonia', 'Romania', 'Niger', 'Nepal', 'Togo', 'Finland',
       'Fiji', 'Ghana', 'Maldives', 'Mauritius', 'Hungary', 'Laos',
       'Papua New Guinea', 'China', 'Liberia', 'Republic of the Congo',
       'Mali', 'Yemen', 'Rwanda', 'Sierra Leone', 'Cameroon', 'Cuba',
       'Croatia', 'Georgia', 'Azerbaijan', 'Madagascar', 'Lithuania',
       'Burundi', 'Ukraine', 'Moldova', 'Armenia', 'Russia',
       'Ivory Coast', 'Kazakhstan', 'Antigua and Barbuda',
       'Bosnia-Herzegovina', 'Equatorial Guinea', 'Tajikistan', 'Malawi',
       'Uzbekistan', 'Latvia', 'Estonia', 'Vietnam', 'Comoros', 'Benin',
       'Slovak Republic', 'Macedonia', 'Wallis and Futuna', 'Belarus',
       'Czech Republic', 'Slovenia', 'Gambia', 'North Korea', 'Eritrea',
       'St. Kitts and Nevis', 'French Polynesia', 'Macau', 'Kyrgyzstan',
       'Vanuatu', 'Democratic Republic of the Congo', 'Kosovo',
       'Solomon Islands', 'East Timor', 'St. Lucia', 'Guinea-Bissau',
       'Montenegro', 'International', 'Turkmenistan', 'Serbia-Montenegro',
       'Bhutan', 'Serbia', 'South Sudan'], dtype=object)

In [14]:
# remove rows with null country codes
terror_df = terror_df.dropna(subset=['country_code'])

In [15]:
# merge the two dataframes
merged_df = terror_df.merge(df, left_on=['country_code', 'year-month'], right_on=['LOCATION', 'TIME'])
merged_df.dropna(subset=['diffs']).head(20)

         eventid  iyear  imonth  iday  ...     TIME      Value Flag Codes    diffs
33  200505020002   2005       5     2  ...  2005-05  100.17060        NaN -0.07760
34  200505050002   2005       5     5  ...  2005-05  100.33530        NaN -0.15630
35  200505100012   2005       5    10  ...  2005-05   99.61779        NaN -0.13482
36  200505150015   2005       5    15  ...  2005-05   99.61779        NaN -0.13482
37  200505230008   2005       5    23  ...  2005-05   99.61779        NaN -0.13482
38  200505230009   2005       5    23  ...  2005-05   99.61779        NaN -0.13482
39  200505290001   2005       5    29  ...  2005-05   99.61779        NaN -0.13482
40  200505290002   2005       5    29  ...  2005-05   99.61779        NaN -0.13482
41  200505290003   2005       5    29  ...  2005-05   99.61779        NaN -0.13482
42  200505290004   2005       5    29  ...  2005-05   99.61779        NaN -0.13482
43  200505290005   2005       5    29  ...  2005-05   99.61779        NaN -0.13482
44  200505240002   2005       5    24  ...  2005-05   99.47002        NaN -0.36768
45  200505240005   2005       5    24  ...  2005-05   99.25113        NaN -0.59620
46  200505240006   2005       5    24  ...  2005-05   99.25113        NaN -0.59620
47  200506090005   2005       6     9  ...  2005-06   99.49104        NaN -0.17102
48  200506150005   2005       6    15  ...  2005-06   99.49104        NaN -0.17102
49  200506260002   2005       6    26  ...  2005-06  100.12930        NaN -0.11560
50  200507010008   2005       7     1  ...  2005-07  100.09710        NaN -0.11820
51  200507070001   2005       7     7  ...  2005-07  100.09710        NaN -0.11820
52  200507070002   2005       7     7  ...  2005-07  100.09710        NaN -0.11820

[20 rows x 146 columns]

In [16]:
terror_df.weaptype1.value_counts()

6     6675
5     3145
8     3049
13     551
9      388
2       67
10      44
12      37
11      33
1       28
3       12
7        6
Name: weaptype1, dtype: int64

In [ ]:
terror_df[]